# Generated by Django 6.0.1 on 2026-03-10 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('ID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('Location', models.CharField(max_length=100)),
                ('Telephone', models.CharField(max_length=15)),
            ],
        ),
    ]
