# Generated by Django 6.0.1 on 2026-03-10 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('ID', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=255)),
                ('Author', models.CharField(max_length=255)),
                ('Price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Stock', models.IntegerField()),
                ('ISBN', models.CharField(max_length=255)),
                ('Image_url', models.URLField(max_length=255)),
                ('Weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Dimensions', models.CharField(max_length=255)),
                ('Amazon_url', models.URLField(max_length=255)),
                ('RowID', models.CharField(max_length=255)),
                ('BookSupplier_ID', models.CharField(max_length=255)),
            ],
        ),
    ]
