# Generated by Django 6.0.1 on 2026-03-10 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notificaton',
            fields=[
                ('ID', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('Context', models.TextField()),
                ('Type', models.CharField(max_length=255)),
                ('Created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User_notification',
            fields=[
                ('pk', models.CompositePrimaryKey('User_ID', 'Notification_ID', blank=True, editable=False, primary_key=True, serialize=False)),
                ('User_ID', models.CharField(max_length=255)),
                ('Status', models.IntegerField(default=0)),
                ('Notification_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.notificaton')),
            ],
        ),
    ]
