# Generated by Django 6.0.1 on 2026-03-10 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deliveryman',
            fields=[
                ('ID', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=255)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('Password', models.CharField(max_length=255)),
                ('House_number', models.CharField(max_length=255)),
                ('Street', models.CharField(max_length=255)),
                ('District', models.CharField(max_length=255)),
                ('Province', models.CharField(max_length=255)),
                ('Country', models.CharField(max_length=255)),
                ('Telephone', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Shipping',
            fields=[
                ('ID', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('Method', models.CharField(max_length=255)),
                ('Fee', models.FloatField()),
                ('Address', models.CharField(max_length=255)),
                ('Phone_number', models.CharField(max_length=255)),
                ('Created_at', models.DateTimeField(auto_now_add=True)),
                ('Order_ID', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Shipping_track',
            fields=[
                ('ID', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('Status', models.CharField(max_length=255)),
                ('Location', models.CharField(max_length=255)),
                ('Time', models.DateTimeField(auto_now_add=True)),
                ('Shipping_ID', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Shipping_delivery',
            fields=[
                ('pk', models.CompositePrimaryKey('Shipping_ID', 'Deliveryman_ID', blank=True, editable=False, primary_key=True, serialize=False)),
                ('Start_location', models.CharField(max_length=255)),
                ('End_location', models.CharField(max_length=255)),
                ('Start_time', models.DateTimeField(auto_now_add=True)),
                ('End_time', models.DateTimeField()),
                ('Deliveryman_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.deliveryman')),
                ('Shipping_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.shipping')),
            ],
        ),
    ]
