# Generated by Django 6.0.1 on 2026-03-10 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('ID', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('Total_amount', models.FloatField()),
                ('Created_at', models.DateTimeField(auto_now_add=True)),
                ('Address', models.CharField(max_length=255)),
                ('Phone_number', models.CharField(max_length=20)),
                ('Customer_ID', models.CharField(max_length=255)),
            ],
        ),
    ]
