# Generated by Django 6.0.1 on 2026-03-10 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory_staff',
            fields=[
                ('ID', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=255)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('Password', models.CharField(max_length=255)),
                ('House_number', models.CharField(max_length=255)),
                ('Street', models.CharField(max_length=255)),
                ('District', models.CharField(max_length=255)),
                ('Province', models.CharField(max_length=255)),
                ('Country', models.CharField(max_length=255)),
                ('Telephone', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('ID', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=255)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('Telephone', models.CharField(max_length=255)),
                ('Location', models.CharField(max_length=255)),
                ('Quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('ID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Handle_at', models.DateTimeField(auto_now_add=True)),
                ('Total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Inventory_staff_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.inventory_staff')),
            ],
        ),
        migrations.CreateModel(
            name='Book_supplier',
            fields=[
                ('ID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Description', models.CharField(max_length=255)),
                ('BookID', models.CharField(max_length=10)),
                ('Receipt_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.receipt')),
                ('Supplier_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.supplier')),
            ],
        ),
    ]
