# Generated by Django 6.0.1 on 2026-03-10 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recommender_AI_system',
            fields=[
                ('ID', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('ModelName', models.CharField(max_length=100)),
                ('Type', models.CharField(max_length=100)),
                ('Layer', models.IntegerField()),
            ],
        ),
    ]
