# Generated by Django 6.0.1 on 2026-03-10 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Salecode',
            fields=[
                ('ID', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('Code', models.CharField(max_length=255)),
                ('Created_at', models.DateTimeField(auto_now_add=True)),
                ('Start_Day', models.DateTimeField(auto_now_add=True)),
                ('End_Day', models.DateTimeField(auto_now_add=True)),
                ('Discount', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Customer_salecode',
            fields=[
                ('pk', models.CompositePrimaryKey('Customer_ID', 'Salecode_ID', blank=True, editable=False, primary_key=True, serialize=False)),
                ('Customer_ID', models.CharField(max_length=255, unique=True)),
                ('Quantity', models.IntegerField(default=0)),
                ('Status', models.IntegerField(default=0)),
                ('Salecode_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.salecode')),
            ],
        ),
        migrations.CreateModel(
            name='Salecode_Order',
            fields=[
                ('pk', models.CompositePrimaryKey('Order_ID', 'Customer_ID', 'Salecode_ID', blank=True, editable=False, primary_key=True, serialize=False)),
                ('Order_ID', models.CharField(max_length=255, unique=True)),
                ('Customer_ID', models.CharField(max_length=255)),
                ('Salecode_ID', models.CharField(max_length=255)),
                ('Customer_salecode_ID', models.ForeignObject(from_fields=['Customer_ID', 'Salecode_ID'], on_delete=django.db.models.deletion.CASCADE, to='app.customer_salecode', to_fields=['Customer_ID', 'Salecode_ID'])),
            ],
        ),
    ]
