# Generated by Django 6.0.1 on 2026-03-10 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('ID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Created_at', models.DateTimeField(auto_now_add=True)),
                ('Note', models.CharField(max_length=255)),
                ('Status', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SalaryReceipt',
            fields=[
                ('ID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Created_at', models.DateTimeField(auto_now_add=True)),
                ('Total_amount', models.FloatField()),
                ('Currency', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('ID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Type', models.CharField(max_length=20)),
                ('Start', models.DateTimeField(auto_now_add=True)),
                ('End', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('ID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254)),
                ('Password', models.CharField(max_length=100)),
                ('Telephone', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Registration_Shift',
            fields=[
                ('pk', models.CompositePrimaryKey('Registration_ID', 'Shift_ID', blank=True, editable=False, primary_key=True, serialize=False)),
                ('Registration_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.registration')),
                ('Shift_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.shift')),
            ],
        ),
        migrations.CreateModel(
            name='OfficialWorkingShift',
            fields=[
                ('ID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Description', models.CharField(max_length=100)),
                ('Handle_at', models.DateTimeField(auto_now_add=True)),
                ('Registration_ID', models.CharField(max_length=10)),
                ('Shift_ID', models.CharField(max_length=10)),
                ('Registration_Shift_ID', models.ForeignObject(from_fields=['Registration_ID', 'Shift_ID'], on_delete=django.db.models.deletion.CASCADE, to='app.registration_shift', to_fields=['Registration_ID', 'Shift_ID'])),
            ],
        ),
        migrations.CreateModel(
            name='RecordWorking',
            fields=[
                ('ID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Start_time', models.DateTimeField(auto_now_add=True)),
                ('End_time', models.DateTimeField(auto_now_add=True)),
                ('OfficialWorkingShift_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.officialworkingshift')),
                ('SalaryReceipt_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.salaryreceipt')),
            ],
        ),
        migrations.AddField(
            model_name='registration',
            name='User_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user'),
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('ID', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('House_number', models.CharField(max_length=255)),
                ('Street', models.CharField(max_length=255)),
                ('District', models.CharField(max_length=255)),
                ('Province', models.CharField(max_length=255)),
                ('Country', models.CharField(max_length=255)),
                ('Telephone', models.CharField(max_length=255)),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
        ),
    ]
