# Generated by Django 6.0.1 on 2026-03-10 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('ID', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('Score', models.IntegerField()),
                ('Created_at', models.DateTimeField(auto_now_add=True)),
                ('Book_ID', models.CharField(max_length=255)),
                ('Customer_ID', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('ID', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('Context', models.TextField()),
                ('Created_at', models.DateTimeField(auto_now_add=True)),
                ('Book_ID', models.CharField(max_length=255)),
                ('Customer_ID', models.CharField(max_length=255)),
                ('Staff_ID', models.CharField(blank=True, max_length=255, null=True)),
                ('Comment_ID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.comment')),
            ],
        ),
    ]
