# Generated by Django 6.0.1 on 2026-03-10 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('ID', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('Amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Status', models.CharField(max_length=20)),
                ('Created_at', models.DateTimeField(auto_now_add=True)),
                ('Method_name', models.CharField(max_length=20)),
                ('Currency', models.CharField(max_length=10)),
                ('Order_ID', models.CharField(max_length=36)),
            ],
        ),
    ]
