# Generated by Django 6.0.1 on 2026-03-10 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('ID', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=255)),
                ('Total_quantity', models.IntegerField()),
                ('Type', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Shelf',
            fields=[
                ('ID', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=255)),
                ('Quantity', models.IntegerField()),
                ('Type', models.CharField(max_length=255)),
                ('Inventory_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.inventory')),
            ],
        ),
        migrations.CreateModel(
            name='Row',
            fields=[
                ('ID', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=255)),
                ('Quantity', models.IntegerField()),
                ('Type', models.CharField(max_length=255)),
                ('Shelf_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.shelf')),
            ],
        ),
    ]
