# Generated by Django 6.0.1 on 2026-03-10 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='behavior',
            fields=[
                ('ID', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('Action', models.CharField(max_length=255)),
                ('Handle_at', models.DateTimeField(auto_now_add=True)),
                ('Counter', models.IntegerField(default=0)),
                ('Customer_ID', models.CharField(max_length=255)),
                ('Book_ID', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('ID', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=255)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('Password', models.CharField(max_length=255)),
                ('House_number', models.CharField(max_length=255)),
                ('Street', models.CharField(max_length=255)),
                ('District', models.CharField(max_length=255)),
                ('Province', models.CharField(max_length=255)),
                ('Country', models.CharField(max_length=255)),
                ('Telephone', models.CharField(max_length=255)),
            ],
        ),
    ]
